# Author  : Srujan Patil <patilsru@msu.edu>
# Production-ready Docker Compose configuration

version: "3.8"
services:
  # A user-defined name for this container
  flask-app:
    container_name: deploy-assistant
    # Use production Dockerfile for deployment
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # Load environment variables from file
    env_file:
      - docker.env
    # Environment variables (secrets should be in env_file)
    environment:
      - SECRET_KEY=${SECRET_KEY}
    # Production optimizations
    restart: unless-stopped
    # Security: run as non-root user
    user: "1000:1000"
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
