# Author  : Srujan Patil <patilsru@msu.edu>

version: "3.8"
services:
  # A user-defined name for this container
  flask-app:
    container_name: deploy-assistant
    # Indicates that `Dockerfile-dev` should be used for local instantiations
    build:
        context: .
        dockerfile: Dockerfile-dev
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    # Mounts the local directory to docker container as a volume.
    volumes:
      - .:/app
    # Environment variables
    environment:
      - SECRET_KEY=2435d1b74714cf4cdb26e93429d3c5f3007d7d75543b836d3b7fb7f21213a4dc
